"on":
    push:
        branches:
            - main
name: Deploy to letterstory-toolbuilder
jobs:
    porter-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Setup porter
              uses: porter-dev/setup-porter@v0.2.0
            - name: Sync runtime Porter sandbox env
              run: |
                porter env set --group letterstory-toolbuilder-secrets \
                  -s PORTER_API_TOKEN="$PORTER_TOKEN" \
                  -v PORTER_PROJECT_ID="$PORTER_PROJECT" \
                  -v PORTER_CLUSTER_ID="$PORTER_CLUSTER"
              env:
                PORTER_CLUSTER: "6018"
                PORTER_DEPLOYMENT_TARGET_ID: 57c6c7ab-370f-43b9-a1e9-f061af782fdf
                PORTER_HOST: https://dashboard.porter.run
                PORTER_PROJECT: "19766"
                PORTER_TOKEN: ${{ secrets.PORTER_APP_19766_22301 }}
            - name: Build and push desired image
              timeout-minutes: 30
              run: |
                porter app build "$PORTER_APP_NAME" --tag "$GITHUB_SHA" --build-method docker --build-context . --dockerfile ./Dockerfile
                porter app push "$PORTER_APP_NAME" --tag "$GITHUB_SHA"
              env:
                PORTER_APP_NAME: letterstory-toolbuilder
                PORTER_CLUSTER: "6018"
                PORTER_DEPLOYMENT_TARGET_ID: 57c6c7ab-370f-43b9-a1e9-f061af782fdf
                PORTER_HOST: https://dashboard.porter.run
                PORTER_PROJECT: "19766"
                PORTER_TOKEN: ${{ secrets.PORTER_APP_19766_22301 }}
            - name: Roll out without surge
              timeout-minutes: 30
              run: |
                porter apply -f porter.scale-zero.yaml --app "$PORTER_APP_NAME" --tag "$GITHUB_SHA" --no-build --exact --wait
                porter apply -f porter.yaml --app "$PORTER_APP_NAME" --tag "$GITHUB_SHA" --no-build --exact --wait
              env:
                PORTER_APP_NAME: letterstory-toolbuilder
                PORTER_CLUSTER: "6018"
                PORTER_DEPLOYMENT_TARGET_ID: 57c6c7ab-370f-43b9-a1e9-f061af782fdf
                PORTER_HOST: https://dashboard.porter.run
                PORTER_PROJECT: "19766"
                PORTER_TOKEN: ${{ secrets.PORTER_APP_19766_22301 }}
